apiVersion: apps/v1
kind: Deployment
metadata:
  name: dtm-test-go1
  labels:
    app: dtm-test-go1
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: dtm-test-go1
  template:
    metadata:
      labels:
        app: dtm-test-go1
    spec:
      containers:
      - name: dtm-test-go1
        image: "exploitht/dtm-test-go1:{{ .Chart.AppVersion }}"
        ports:
        - containerPort: 8080
